# Generated by Django 5.2.9 on 2026-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_alter_caregiverprofile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
