# Generated by Django 5.2.9 on 2026-01-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0003_alter_caregiverprofile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='caregiver_photos/'),
        ),
    ]
