# Generated by Django 5.2.9 on 2026-03-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0002_parent_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_location_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_location_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
